# Generated by Django 3.1.5 on 2023-03-05 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230305_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.CreateModel(
            name='AttachCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('allowed_suffixes', models.ManyToManyField(related_name='allowed_attach_categories', to='account.Suffix')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='attach_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='account.attachcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='allowed_attach_categories',
            field=models.ManyToManyField(related_name='allowed_categories', to='account.AttachCategory'),
        ),
    ]
