# Generated by Django 3.1.5 on 2023-03-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230305_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='is_private',
        ),
    ]
